name: UsableML
channels:
  - defaults
dependencies:
  - black=23.3.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - libffi=3.4.2
  - mypy_extensions=0.4.3
  - ncurses=6.4
  - openssl=1.1.1t
  - packaging=23.0
  - pathspec=0.10.3
  - pip=23.0.1
  - platformdirs=2.5.2
  - python=3.10.9
  - readline=8.2
  - setuptools=65.6.3
  - sqlite=3.41.1
  - tk=8.6.12
  - tomli=2.0.1
  - wheel=0.38.4
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
      - altair==4.2.2
      - attrs==22.2.0
      - blinker==1.6.1
      - cachetools==5.3.0
      - charset-normalizer==3.1.0
      - click==8.1.3
      - contourpy==1.0.7
      - cycler==0.11.0
      - decorator==5.1.1
      - entrypoints==0.4
      - fonttools==4.39.3
      - gitdb==4.0.10
      - gitpython==3.1.31
      - idna==3.4
      - importlib-metadata==6.3.0
      - jinja2==3.1.2
      - jsonschema==4.17.3
      - kiwisolver==1.4.4
      - markdown-it-py==2.2.0
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - mdurl==0.1.2
      - numpy==1.24.2
      - pandas==1.5.3
      - pillow==9.5.0
      - protobuf==3.20.3
      - pyarrow==11.0.0
      - pydeck==0.8.0
      - pygments==2.15.0
      - pympler==1.0.1
      - pyparsing==3.0.9
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pytz-deprecation-shim==0.1.0.post0
      - pyzmq==25.0.2
      - requests==2.28.2
      - rich==13.3.3
      - seaborn==0.12.2
      - six==1.16.0
      - smmap==5.0.0
      - streamlit==1.21.0
      - toolz==0.12.0
      - tornado==6.2
      - tqdm==4.65.0
      - tzdata==2023.3
      - tzlocal==4.3
      - urllib3==1.26.15
      - validators==0.20.0
      - watchdog==3.0.0
      - zipp==3.15.0
      - zmq==0.0.0